---
title: "Table S4"
output: html_notebook
---


## Import libraries
```{r}
library(tidyverse, quietly = TRUE)
library(stringr, quietly = TRUE)
```

## Import the DE data
```{r}
t7_DE = read.csv('t7_DE.csv', header=T, row.names=1, com='', check.names=F)
t16_DE = read.csv('t16_DE.csv', header=T, row.names=1, com='', check.names=F)
Pulse_DE = read.csv('pulse_DE.csv', header=T, row.names=1, com='', check.names=F)
No_Pulse_DE = read.csv('no_pulse_DE.csv', header=T, row.names=1, com='', check.names=F)
genebank=read.csv("TrinityID_info.csv",header=T,fill=T)
```

## Add a column "GeneID"
```{r}
t7_DE =rownames_to_column(t7_DE)
t16_DE =rownames_to_column(t16_DE)
Pulse_DE =rownames_to_column(Pulse_DE)
No_Pulse_DE =rownames_to_column(No_Pulse_DE)

colnames(t7_DE)[colnames(t7_DE)=="rowname"] = "GeneID"
colnames(t16_DE)[colnames(t16_DE)=="rowname"] = "GeneID"
colnames(Pulse_DE)[colnames(Pulse_DE)=="rowname"] = "GeneID"
colnames(No_Pulse_DE)[colnames(No_Pulse_DE)=="rowname"] = "GeneID"
```

## Add a column "DE" indicating whether the gene is DE at this dataset
```{r}
t7_DE$DE=0
t7_DE$DE[t7_DE$GeneID %in% t7_DEG] = 1

t16_DE$DE=0
t16_DE$DE[t16_DE$GeneID %in% t16_DEG] = 1

Pulse_DE$DE=0
Pulse_DE$DE[Pulse_DE$GeneID %in% Pulse_DEG] = 1
Pulse_DE

No_Pulse_DE$DE=0
No_Pulse_DE$DE[No_Pulse_DE$GeneID %in% No_Pulse_DEG] = 1
```


## Find the overlapped genes in both figures
```{r}
overlap_both <- intersect(total_DE_genes,total_DE_genes2)
```

## Merge datasets
```{r}
#Merge the tables(t3_full_DE_info and t12_full_DE_info)
combined_table <- inner_join(t7_DE,t16_DE,by="GeneID",suffix = c("_t7","_t16"))
combined_table <- combined_table[combined_table$GeneID %in% total_DE_genes,]
combined_table
#Add a column DE_color indicating de at which dataset
combined_table$DE_t7[combined_table$DE_t7==1]=2
combined_table$DE_t7 <- as.numeric(as.character(combined_table$DE_t7))
combined_table$DE_t16 <- as.numeric(as.character(combined_table$DE_t16))
combined_table$DE_color <- combined_table$DE_t7 + combined_table$DE_t16
combined_table$DE_color[combined_table$DE_color==2]="et7"
combined_table$DE_color[combined_table$DE_color==1]="et16"
combined_table$DE_color[combined_table$DE_color==3]="both"
```

```{r}
#Merge the two datasets(Pulse_full_DE_info and No_Pulse_full_DE_info)
combined_table2 <- inner_join(Pulse_DE,No_Pulse_DE,by="GeneID",suffix = c("_Pulse","_No_Pulse"))
combined_table2 <- combined_table2[combined_table2$GeneID %in% total_DE_genes2,]

#Add a column indicating de at which dataset
combined_table2$DE_Pulse[combined_table2$DE_Pulse==1]=2
combined_table2$DE_Pulse <- as.numeric(as.character(combined_table2$DE_Pulse))
combined_table2$DE_No_Pulse <- as.numeric(as.character(combined_table2$DE_No_Pulse))
combined_table2$DE_color <- combined_table2$DE_Pulse + combined_table2$DE_No_Pulse
combined_table2$DE_color[combined_table2$DE_color==2]="Pulse"
combined_table2$DE_color[combined_table2$DE_color==1]="No Pulse"
combined_table2$DE_color[combined_table2$DE_color==3]="both"
```

## Add a column "overlap" indicating overlapped in both figures or not
```{r}
combined_table$overlap = "no"
combined_table$overlap[combined_table$GeneID %in% overlap_both]="yes"

combined_table2$overlap = "no"
combined_table2$overlap[combined_table2$GeneID %in% overlap_both]="yes"
```

## Make Table S2
```{r}
result1 <- subset(combined_table[combined_table$logFC_t7<0,])
result2 <- subset(result1[result1$logFC_t16>0,])
result2$DE_t7[result2$DE_t7=="0"]="no"
result2$DE_t7[result2$DE_t7=="2"]="yes"
result2$DE_t16[result2$DE_t16=="0"]="no"
result2$DE_t16[result2$DE_t16=="1"]="yes"
t7t16result<-merge(result2, genebank, by="GeneID")
t7t16result<-t7t16result[,c("GeneID","logFC_t7","LR_t7","PValue_t7","FDR_t7","DE_t7","logFC_t16","LR_t16","PValue_t16","FDR_t16","DE_t16","match_id","pfam_def","pfam_go","sw_def","sw_go")]
t7t16result
write.csv(t7t16result,file="second_quadrant_t7t16.csv")
```

```{r}
result3 <- subset(combined_table2[combined_table2$logFC_Pulse<0,])
result4 <- subset(result3[result3$logFC_No_Pulse>0,])
result4$DE_Pulse[result4$DE_Pulse=="0"]="no"
result4$DE_Pulse[result4$DE_Pulse=="2"]="yes"
result4$DE_No_Pulse[result4$DE_No_Pulse=="0"]="no"
result4$DE_No_Pulse[result4$DE_No_Pulse=="1"]="yes"
pulsenopulse_result<-merge(result4, genebank, by="GeneID")
pulsenopulse_result<-pulsenopulse_result[,c("GeneID","logFC_Pulse","LR_Pulse","PValue_Pulse","FDR_Pulse","DE_Pulse","logFC_No_Pulse","LR_No_Pulse","PValue_No_Pulse","FDR_No_Pulse","DE_No_Pulse","match_id","pfam_def","pfam_go","sw_def","sw_go")]
pulsenopulse_result
write.csv(pulsenopulse_result,file="second_quadrant_pulsenopulse.csv")
```



