---
title: "Figure 4"
output: html_notebook
---


## Import the libraries
```{r}
library("ggpubr")
library("Hmisc")
library("corrplot")
library("reshape2")
library("dplyr")
library("ggplot2")
library("tibble")
library("readxl")
```


## Figure 4A
```{r}
clock = read.csv("Clock_with_logFC.csv")
clock$Pvalue_2sig = signif(clock$Pvalue, 2)
clock$DE = clock$Pvalue<0.05
clock$DE[clock$DE]="yes"
clock$DE[clock$DE==FALSE]="no"
clock$DE[is.na(clock$DE)]="NA"
clock$logFC[is.na(clock$logFC)]=0
clock$Pvalue_2sig[is.na(clock$Pvalue_2sig)]="NA"
```

```{r  fig.height=7, fig.width=8.5}
logFC_comp <- ggplot(clock, aes(y=logFC, x=Clock_gene, fill=Comparison)) +
  geom_col(position="dodge")  +
  #theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  #scale_alpha_manual("DE gene",values=c(1,0.5,0.2),breaks=c("yes","no","N/A"))+
  scale_fill_manual(values=c("green","red","purple","yellow"),breaks=c("logFC_t7.t16_Pulse","logFC_t7.t16_NoPulse","logFC_Pulse.NoPulse_t7","logFC_Pulse.NoPulse_t16"))+
  xlab("Clcok Gene")+
  geom_text(aes(Clock_gene,label=Pvalue_2sig,y=2), position = position_dodge(width = 1)) +
  coord_flip(xlim = c(1,7.3))+
  annotate(geom="text", x=7.7, y=2, label="P value",color="Black")

logFC_comp
```


## Figure 4B
```{r}
TPM = read_excel("Clock_tpm.xlsx",sheet=1,col_names = TRUE,col_types = NULL,  skip = 0)
```

```{r}
res = rcorr(as.matrix(TPM[,c(2,3,4,5,6,7,8)]))
```

```{r}
get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
}

pmat = round(res$P,2)
upper_res <- get_upper_tri(pmat)
melted_pmat <- melt(upper_res, na.rm = TRUE)
melted_pmat=rownames_to_column(melted_pmat)

cormat = round(res$r,2)
upper_res <- get_upper_tri(cormat)
melted_cormat <- melt(upper_res, na.rm = TRUE)
melted_cormat=rownames_to_column(melted_cormat)

mat = left_join(melted_cormat,melted_pmat,by="rowname",suffix=c("cor","p"))
mat = mat[,c(1,2,3,4,7)]
colnames(mat)=c("index","Var1","Var2","cor","p")
mat$p = paste("(",mat$p,")")
```

```{r}
ggheatmap <- ggplot(mat, aes(Var2, Var1, fill = cor))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Pearson\nCorrelation") +
 coord_fixed()+ 
  geom_text(aes(Var2, Var1, label = cor), color = "black", size = 4, vjust = 0) +
  geom_text(aes(label = p),size=3, vjust = 1.5) +
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.5, 0.75),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))
  #+  ggtitle("Correlation coefficients among the 7 canonical clock genes")
# Print the heatmap
print(ggheatmap)
```


## Combine 4A and 4B

```{r fig.height=6,fig.width=16}
ggarrange(logFC_comp,ggheatmap,ncol=2,nrow=1,common.legend=F,labels=c("(A)","(B)"))
```
